### ISSUE TITLE
broken due to ancient nixpkgs in `matthewbauer/nix-bundle`

### ISSUE THREAD

**Issue by cafkafk** [NixOS/bundlers#22]
Currently the nixpkgs version in `nix-bundle` is so old that the command fails without --option deprecated-features url-literals.

A temporary workaround would be to specify a nixpkgs input in this repository and make `nix-bundle` follow that until it's fixed. `nix-bundle` has several stale PRs and hasn't been touched in 8 months, so it likely will be worth it to make such a temporary change if the maintainer doesn't reply.

See also: https://github.com/matthewbauer/nix-bundle/issues/109

**Comment by Artturin** [comment]
https://github.com/nix-community/nix-bundle/pull/110
